version: "3.4"

networks:
  nerdstore-networking:

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-nerdstore-enterprise
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    networks:
      - nerdstore-networking

  sql-server:
    image: nerdstore-enterprise/nerdstore-mssql:latest
    container_name: nerdstore-mssql
    build:
      context: "../sql"
      dockerfile: "./Dockerfile"
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"
    networks:
      - nerdstore-networking

  nerdstore-server: 
    image: nerdstore-enterprise/nerdstore-server:latest
    container_name: nerdstore-server
    build: 
      context: "./"
      dockerfile: "./nginx/Dockerfile"
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - web-mvc 
    networks: 
      - nerdstore-networking

  web-mvc:
    image: nerdstore-enterprise/nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build:
      context: "../src"
      dockerfile: "./Web/MVC/NSE.WebApp.MVC/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7064;http://*:5251
    depends_on:
      - api-catalogo
      - api-identidade
      - api-cliente
      - api-bff-compras
    networks:
      - nerdstore-networking

  api-bff-compras:
    image: nerdstore-enterprise/nerdstore-api-bff-compras:latest
    container_name: nerdstore-api-bff-compras
    build:
      context: "../src"
      dockerfile: "./api-gateways/Compras/NSE.Bff.Compras/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:8080;http://*:5011
      - ASPNETCORE_Kestrel__Certificates__Default__Password=urubu100
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:https:ro
    depends_on:
      - api-identidade
      - api-catalogo
      - api-cliente
      - api-carrinho
      - api-pedido
    networks:
      - nerdstore-networking

  api-catalogo:
    image: nerdstore-enterprise/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: "../src"
      dockerfile: "./Services/Catalogo/NSE.Catalogo.Api/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5000;http://*:7000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=urubu100
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:https:ro
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade
    networks:
      - nerdstore-networking

  api-identidade:
    image: nerdstore-enterprise/nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    build:
      context: "../src"
      dockerfile: "./Services/Identidade/NSE.Identidade.API/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7213;http://*:5140
      - ASPNETCORE_Kestrel__Certificates__Default__Password=urubu100
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:https:ro
    depends_on:
      - rabbitmq
      - sql-server
    networks:
      - nerdstore-networking

  api-cliente:
    image: nerdstore-enterprise/nerdstore-api-cliente:latest
    container_name: nerdstore-api-cliente
    build:
      context: "../src"
      dockerfile: "./Services/Cliente/NSE.Cliente.API/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7276;http://+:5072
      - ASPNETCORE_Kestrel__Certificates__Default__Password=urubu100
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:https:ro
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade
    networks:
      - nerdstore-networking

  api-carrinho:
    image: nerdstore-enterprise/nerdstore-api-carrinho:latest
    container_name: nerdstore-api-carrinho
    build:
      context: "../src"
      dockerfile: "./Services/Carrinho/NSE.Carrinho.Api/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7263;http://+:5018
      - ASPNETCORE_Kestrel__Certificates__Default__Password=urubu100
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:https:ro
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade
    networks:
      - nerdstore-networking
  
  api-pedido:
    image: nerdstore-enterprise/nerdstore-api-pedido:latest
    container_name: nerdstore-api-pedido
    build:
      context: "../src"
      dockerfile: "./Services/Pedido/NSE.Pedido.API/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7002;http://+:5002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=urubu100
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:https:ro
    depends_on:
       - rabbitmq
       - sql-server
       - api-identidade
    networks:
      - nerdstore-networking   
  
  api-pagamento:
    image: nerdstore-enterprise/nerdstore-api-pagamento:latest
    container_name: nerdstore-api-pagamento
    build: 
      context: "../src"
      dockerfile: "./Services/Pagamento/NSE.Pagamento.API/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+7257;http://+:5112
      - ASPNETCORE_Kestrel__Certificates__Default__Password=urubu100
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:https:ro
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade
    networks:
      - nerdstore-networking