version: "3.4"

networks:
  nerdstore-networking:

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-nerdstore-enterprise
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nerdstore-networking

  sql-server:
    image: nerdstore-enterprise/nerdstore-mssql:latest
    container_name: nerdstore-mssql
    build:
      context: "../sql"
      dockerfile: "./Dockerfile"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"
    networks:
      - nerdstore-networking

  web-mvc:
    image: nerdstore-enterprise/nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build:
      context: "../src"
      dockerfile: "./Web/MVC/NSE.WebApp.MVC/Dockerfile"
    ports:
      - "7064:7064"
      - "5251:5251"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5251
    depends_on:
      - api-catalogo
    networks:
      - nerdstore-networking

  api-catalogo:
    image: nerdstore-enterprise/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: "../src"
      dockerfile: "./Services/Catalogo/NSE.Catalogo.Api/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:7000
    depends_on:
      - rabbitmq
      - sql-server
    networks:
      - nerdstore-networking
