// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSE.Carrinho.Api.Data;

#nullable disable

namespace NSE.Carrinho.API.Data.Migrations
{
    [DbContext(typeof(ShoppingCartContext))]
    [Migration("20230325125406_Voucher-correcao")]
    partial class Vouchercorrecao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NSE.Carrinho.Api.Domain.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Name")
                        .HasColumnType("Varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("NSE.Carrinho.Api.Domain.CustomerShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasVoucher")
                        .HasColumnType("bit");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_cliente");

                    b.ToTable("CustomerShoppingCarts");
                });

            modelBuilder.Entity("NSE.Carrinho.Api.Domain.CartItem", b =>
                {
                    b.HasOne("NSE.Carrinho.Api.Domain.CustomerShoppingCart", "CustomerShoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId")
                        .IsRequired();

                    b.Navigation("CustomerShoppingCart");
                });

            modelBuilder.Entity("NSE.Carrinho.Api.Domain.CustomerShoppingCart", b =>
                {
                    b.OwnsOne("NSE.Carrinho.Api.Domain.Voucher", "Voucher", b1 =>
                        {
                            b1.Property<Guid>("CustomerShoppingCartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .HasMaxLength(50)
                                .HasColumnType("Varchar(50)")
                                .HasColumnName("VoucherCode");

                            b1.Property<decimal?>("Discount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("VoucherDiscount");

                            b1.Property<int>("DiscountType")
                                .HasColumnType("int");

                            b1.Property<decimal?>("Percentage")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("VoucherPercentage");

                            b1.HasKey("CustomerShoppingCartId");

                            b1.ToTable("CustomerShoppingCarts");

                            b1.WithOwner()
                                .HasForeignKey("CustomerShoppingCartId");
                        });

                    b.Navigation("Voucher")
                        .IsRequired();
                });

            modelBuilder.Entity("NSE.Carrinho.Api.Domain.CustomerShoppingCart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
